# Generated by Django 3.2.4 on 2021-06-27 19:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
