# Generated by Django 3.2.4 on 2021-07-02 13:45

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contents',
            new_name='contents_ck',
        ),
        migrations.AddField(
            model_name='article',
            name='contents_md',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='editor',
            field=models.CharField(default='CK', max_length=2, verbose_name='Редактор статьи'),
            preserve_default=False,
        ),
    ]
