# Generated by Django 3.2.4 on 2021-06-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_article_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contents',
        ),
    ]
