# Generated by Django 3.2.4 on 2021-06-28 04:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_article_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='asdf'),
            preserve_default=False,
        ),
    ]
