# Generated by Django 3.2.4 on 2021-07-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_articleviews_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sound',
            field=models.ImageField(blank=True, upload_to='article_sound'),
        ),
    ]
