# Generated by Django 3.2.4 on 2021-07-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_article_id'),
        ('mainapp', '0004_alter_article_publication_date'),
    ]

    operations = [
    ]
