# Generated by Django 3.2.4 on 2021-08-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_article_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sound',
            field=models.ImageField(blank=True, default='', upload_to='media', verbose_name='Озвученная статья'),
        ),
    ]
