# Generated by Django 3.2.4 on 2021-06-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0005_alter_article_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_puslished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_success_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
