# Generated by Django 3.2.4 on 2021-06-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210628_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_puslished',
            new_name='is_published',
        ),
    ]
