# Generated by Django 3.2.4 on 2021-06-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0007_rename_is_puslished_article_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_success_moderation',
        ),
        migrations.AddField(
            model_name='article',
            name='is_moderation_in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
