# Generated by Django 3.2.4 on 2021-06-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210628_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_moderation_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
