# Generated by Django 3.2.4 on 2021-06-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0009_alter_article_is_moderation_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2021-01-01'),
            preserve_default=False,
        ),
    ]
