# Generated by Django 3.2.4 on 2021-06-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_article_id'),
        ('mainapp', '0010_article_created_at'),
    ]

    operations = [
    ]
