# Generated by Django 3.2.4 on 2021-06-28 18:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0010_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
