# Generated by Django 3.2.4 on 2021-06-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsbranch',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='commentsbranch',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commentsapp.commentsbranch'),
        ),
        migrations.AlterField(
            model_name='commentsbranch',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текст комментария'),
        ),
    ]
