# Generated by Django 3.2.4 on 2021-07-06 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsbranch',
            name='rating_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
