# Generated by Django 3.2.4 on 2021-06-29 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0011_alter_article_contents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentsapp', '0003_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeArticle',
        ),
        migrations.AddField(
            model_name='commentsbranch',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.article'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LikeComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentsapp.commentsbranch')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
