# Generated by Django 3.2.4 on 2021-07-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commentsapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsbranch',
            name='is_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
