# Generated by Django 3.2.4 on 2021-07-02 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 14, 44, 4, 548362, tzinfo=utc), verbose_name='Время действия кода активации'),
        ),
        migrations.AlterField(
            model_name='geekhubuser',
            name='article_redactor',
            field=models.CharField(choices=[('MD', 'markdown'), ('CK', 'сkeditor')], default='CK', max_length=2, verbose_name='Редактор статей'),
        ),
    ]
