# Generated by Django 3.2.4 on 2021-08-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='usersapp.geekhubuser')),
                ('notify_article_comments',
                 models.BooleanField(default=True, verbose_name='Уведомления о комментариях к статьям')),
                ('notify_article_change_status',
                 models.BooleanField(default=True, verbose_name='Уведомления об изменении статуса статьи')),
                ('notify_moderator_messages',
                 models.BooleanField(default=True, verbose_name='Уведомления о сообщениях при модерации')),
                ('notify_complaints_against_article_status',
                 models.BooleanField(default=True, verbose_name='Уведомления о статусе жалобы на статью')),
                ('notify_complaints_against_comment_status',
                 models.BooleanField(default=True, verbose_name='Уведомление о статусе жалобы на комментарий')),
            ],
        ),
    ]
