# Generated by Django 3.2.4 on 2021-06-18 19:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geekhubuserprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='geekhubuserprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'М'), ('W', 'Ж')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='geekhubuserprofile',
            name='user_information',
            field=models.CharField(blank=True, max_length=512, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 19, 31, 26, 561886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='geekhubuserprofile',
            name='owner_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                       verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='geekhubuserprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фотография профиля'),
        ),
    ]
