# Generated by Django 3.2.4 on 2021-07-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(null=True, verbose_name='Время действия кода активации'),
        ),
    ]
