# Generated by Django 3.2.4 on 2021-07-21 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid
from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 13, 30, 17, 548209, tzinfo=utc), verbose_name='Время действия кода активации'),
        ),
        migrations.AlterField(
            model_name='geekhubuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
