# Generated by Django 3.2.4 on 2021-07-21 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_auto_20210721_1630'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 16, 32, 32, 231923, tzinfo=utc), verbose_name='Время действия кода активации'),
        ),
    ]
