# Generated by Django 3.2.4 on 2021-07-03 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 6, 3, 558002, tzinfo=utc), verbose_name='Время действия кода активации'),
        ),
    ]
