# Generated by Django 3.2.4 on 2021-08-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='geekhubuser',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='ID Telegram'),
        ),
    ]
