# Generated by Django 3.2.4 on 2021-07-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_auto_20210702_1645'),
        ('usersapp', '0005_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
    ]
