# Generated by Django 3.2.4 on 2021-07-06 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 21, 1, 35, 968215, tzinfo=utc), verbose_name='Время действия кода активации'),
        ),
    ]
