# Generated by Django 3.2.4 on 2021-06-19 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('usersapp', '0006_auto_20210618_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 15, 47, 13, 500450, tzinfo=utc)),
        ),
    ]
