# Generated by Django 3.2.4 on 2021-07-11 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0007_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockingByIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='Неудачных попыток')),
                ('time_unblock', models.DateTimeField(blank=True, verbose_name='Время разблокировки')),
                ('blocking_status', models.BooleanField(default=False, verbose_name='Статус блокировки')),
            ],
            options={
                'db_table': 'BlockingByIp',
            },
        ),
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 17, 25, 5, 852452, tzinfo=utc), verbose_name='Время действия кода активации'),
        ),
    ]
