# Generated by Django 3.2.4 on 2021-06-19 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('usersapp', '0009_auto_20210619_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 21, 45, 5, 776834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='geekhubuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
