# Generated by Django 3.2.4 on 2021-06-19 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('usersapp', '0010_auto_20210619_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 21, 59, 32, 953261, tzinfo=utc)),
        ),
    ]
