# Generated by Django 3.2.4 on 2021-06-20 06:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('usersapp', '0011_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 7, 49, 27, 507680, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='geekhubuserprofile',
            name='owner_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                       verbose_name='Пользователь'),
        ),
    ]
