# Generated by Django 3.2.4 on 2021-06-20 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('usersapp', '0012_auto_20210620_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 7, 58, 9, 825006, tzinfo=utc)),
        ),
    ]
