# Generated by Django 3.2.4 on 2021-06-20 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('usersapp', '0015_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='geekhubuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='geekhubuser',
            name='gender',
            field=models.CharField(choices=[('O', 'другой'), ('M', 'мужской'), ('W', 'женский')], default='O',
                                   max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='geekhubuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Фотография профиля'),
        ),
        migrations.AddField(
            model_name='geekhubuser',
            name='user_information',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 11, 0, 17, 123723, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='GeekHubUserProfile',
        ),
    ]
