# Generated by Django 3.2.4 on 2021-06-27 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0037_auto_20210627_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 21, 44, 16, 229124, tzinfo=utc), verbose_name='Время действия кода активации'),
        ),
    ]
