# Generated by Django 3.2.4 on 2021-06-28 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0042_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 9, 7, 2, 59660, tzinfo=utc), verbose_name='Время действия кода активации'),
        ),
    ]
