# Generated by Django 3.2.4 on 2021-06-29 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('usersapp', '0051_alter_geekhubuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geekhubuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 19, 6, 45, 519141, tzinfo=utc),
                                       verbose_name='Время действия кода активации'),
        ),
    ]
