# Generated by Django 3.2.4 on 2021-07-13 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ratingsapp', '0002_ratingcount_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingcount',
            options={'verbose_name': 'Счетчик рейтинга', 'verbose_name_plural': 'Счетчики рейтинга'},
        ),
    ]
